import {
  AirVent,
  BadgeCheck,
  Building2,
  Cable,
  ClipboardCheck,
  Clock,
  Gauge,
  HardHat,
  Network,
  Package,
  Phone,
  PlugZap,
  ReceiptText,
  ShieldCheck,
  Snowflake,
  Store,
  ThermometerSnowflake,
  TrendingUp,
  Truck,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  snowflake: Snowflake,
  zap: Zap,
  wind: Wind,
  wrench: Wrench,
  airvent: AirVent,
  gauge: Gauge,
  "thermometer-snowflake": ThermometerSnowflake,
  truck: Truck,
  plugzap: PlugZap,
  trendingup: TrendingUp,
  receipttext: ReceiptText,
  cable: Cable,
  network: Network,
  package: Package,
  badgecheck: BadgeCheck,
  clock: Clock,
  store: Store,
  shieldcheck: ShieldCheck,
  building: Building2,
  phone: Phone,
  clipboardcheck: ClipboardCheck,
  hardhat: HardHat,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Wrench;
}
